name: David Tang
author: David Tang
description: Thoughts and tutorials on JavaScript, frameworks, testing, and patterns
bio:
paginate: 50
markdown: kramdown
gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed
collections:
  tutorials:
    output: true
    permalink: /:collection/:title
  assignments:
    output: true
    permalink: /:collection/:title
