name: David Tang
author: David Tang
description: Thoughts and tutorials on web programming
bio: Vegan · Software Developer · Teacher · Author
paginate: 15
markdown: kramdown
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed
collections:
  tutorials:
    output: true
    permalink: /:collection/:title
