name: The JS Guy
author: David Tang
description: Thoughts and tutorials on frameworks, testing, patterns, and best practices in JavaScript development
paginate: 5
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed
