name: The JS Guy
author: David Tang
description: Thoughts and tutorials on JavaScript frameworks, testing, and architecture
bio: JavaScript developer passionate about testing and architecture. Ember enthusiast. Instructor at University of Southern California teaching web development classes for ITP.
paginate: 5
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate, jekyll-feed]
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed
